apiVersion: apps/v1
kind: Deployment
metadata:
  name: pstools-nodeport-deployment
spec:
  selector:
    matchLabels:
      app: pstools-app-node
  replicas: 4
  template:
    metadata:
      labels:
        app: pstools-app-node
    spec:
      containers:
        - name: pstools
          image: phillipsj/pstools:v0.2.0
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pstools-app-node
  name: pstools-nodeport-svc
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 30096
      name: http
  selector:
    app: pstools-app-node